sudo: required

language: python

services:
  - mysql

python:
  - 3.6
 
before_install:
 - sudo mysql -e 'CREATE DATABASE wechat_ticket;'
 
install:
 - pip install -r requirements.txt
  
script:
  - cp configs.example.json configs.json


  - python manage.py makemigrations
  - python manage.py migrate

  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell

  - python manage.py test