sudo: required

language: python

services:
  - mysql

python:
  - 3.6
 
 
before_install:
    -mysql -e 'CREATE DATABASE wechat_ticket'
 
install:
 - pip install -r requirements.txt
  
script:
  - cp configs.example.json configs.json
  
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test