sudo: false

language: python

python:
  - 3.6
 
install:
 - pip install -r requirements.txt
  
script:
  - cp configs.example.json configs.json
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test