sudo: required

language: python

services:
  - mysql

python:
  - 3.6
 
before_install:
 - sudo mysql -e 'CREATE DATABASE wechat_ticket;'
 
install:
 - pip install -r requirements.txt
  
script:
  - cp configs.example.json configs.json


  - python manage.py makemigrations
  - python manage.py migrate

  - python manage.py createsuperuser --username admin --email xiaoxd16@163.com
  - 12345678
  - 12345678

  - python manage.py test