sudo: required
language: python
services:
- mysql
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_033a364aed3b_key -iv $encrypted_033a364aed3b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- sudo mysql -e 'CREATE DATABASE wechat_ticket;'
install:
- pip install -r requirements.txt
- pip install uwsgi
script:
- cp configs.example.json configs.json
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
after_success:
- chmod 6-- ~/.ssh/id_rsa
- ssh travis@139.199.124.92 "home/ubuntu/WeChatTicket/deploy.sh"
